[build]
  functions = "proxygemini/functions"

[[redirects]]
  # Changez le chemin "to" pour pointer directement vers le dossier de la fonction (proxygemini)
  from = "/api/*"
  to = "/.netlify/functions/proxygemini"
  status = 200
